# Generated by Django 5.0.4 on 2024-04-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('L', 'Liters'), ('UN', 'Units'), ('KG', 'Kilograms'), ('G', 'Grams')], default='KG', max_length=2),
        ),
    ]
